Fix no jurisdiction taxes
reactioncommerce/api-plugin-taxes-flat-rate pull request #4
Opened 2020-05-13 16:27 UTC by loan-laux

Resolves #issueNumber
Impact: **breaking|critical|major|minor**
Type: **feature|bugfix|performance|test|style|refactor|docs|chore**

## Issue
Description of the issue this PR is solving, why it's happening, and how to reproduce it. This may differ from the original ticket as you now have more information at your disposal.

## Solution
Summarize your solution to the problem. Please include short descriptions of any solutions you tested before arriving at your final solution. This will help reviewers know why you decided to solve this problem in this particular way and will speed up the review process.

If you're solving a UIX related issue, please attach screen-caps or gifs showing how your solution differs from the issue.

## Breaking changes
If you have a breaking changes, list them here, otherwise list none.

Examples of breaking changes include changing file names, moving files, deleting files, renaming functions or exports, or changes to code which might cause previous versions of Reaction or third-party code not to work as expected.

Note any work that you did to mitigate the effect of any breaking changes such as creating migrations, deprecation warnings, etc.

## Testing
1. List the steps needed for testing your change in this section.
2. Assume that testers already know how to start the app, and do the basic setup tasks.
3. Be detailed enough that someone can work through it without being too granular

More detail for what each of these sections should include are available in our [Contributing Docs](https://docs.reactioncommerce.com/reaction-docs/trunk/contributing-to-reaction)

2020-05-17 15:46 UTC, aldeed requested changes
@loan-laux Agree we should remove `country:` line change in favor of the PR that fixes on admin UI side. Maybe changing empty strings to null is a good idea, but it seems like something that should be decided across all of Reaction and implemented the same everywhere to avoid confusion. (But I tend to be in favor of just accepting whatever the client provides as the value rather than trying to be "smart" and ending up just being confusing to client devs.)

Otherwise this looks like a good fix to get merged after you remove that change. Thanks!

2020-05-17 18:25 UTC, loan-laux commented
@aldeed Thanks for the review on a Sunday! Just fixed it. We're good to go.

2020-05-18 00:27 UTC, aldeed approved these changes

2020-05-18 00:27 UTC, merged

2020-05-18 00:28 UTC, rc-publisher commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@reactioncommerce/api-plugin-taxes-flat-rate/v/1.0.1)
- [GitHub release](https://github.com/reactioncommerce/api-plugin-taxes-flat-rate/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: